privacy-tech-lab/privacy-pioneer

src/background/analysis/buildUserData/importSearchData.js
src/background/analysis/classModels.js
src/background/analysis/requestAnalysis/earlyTermination/heuristics.js
src/background/analysis/requestAnalysis/scanHTTP.js
src/background/background.js
src/libs/settings/index.js
src/options/views/settings-view/components/index.js
src/options/views/settings-view/index.js

For now, this just aborts the analysis on >100,00 character requests. The scaffold is there to expand this optimzation. A button is included in the settings page to toggle this functionality.

Optimize Performance (Issue #303/#307) Pipeline With Toggle Button

---

src/background/analysis/requestAnalysis/scanHTTP.js
src/background/analysis/requestAnalysis/searchFunctions.js

Remove disconnect fingerprint search in analysis and search functions.
Close #298 on merge.

#298 remove disconnect fingerprint search

---

src/background/analysis/classModels.js

Updates `privacyLabels` object with approved descriptions and links from #331.
Close #331 on merge.

#331 update privacyLabels object with approved descriptions and links

---

src/libs/tour/index.js

This note was not a part of the original PR corresponding to issue 370.

Note added to tour #370

---

src/assets/keywords.json

Close #359 on merge
Close #360 on merge

Pixel changes implemented

---

architecture_overview.md
src/background/analysis/buildUserData/importSearchData.js

Changes to architecture.md implimented.
Close #378 on merge

architecture md changes #378

---

package-lock.json
package.json

This PR will resolve the Dependabot vulnerabilities reported in the security section of the repo. After doing an `npm install`, I realized that the package-lock file is updated every time even if no dependencies are added. Therefore it may be best to err on the side of caution and remove any changes to the package-lock.json file unless you have added a new dependency. 
Closes #390

Resolved dependabot issues

---

src/options/views/search-view/components/filter-search/index.js

There was an extra parameter in the filter function that was not needed which must have been left when I was refactoring.
closes #388

Removed extra param that caused filter error

---

src/assets/keywords.json

Small additions to add builtwith pixels.
Close #359 on merge.

builtwith additions #359

---

src/libs/indexed-db/updateWatchlist.js

Fixed the watchlist bug #404

---

package.json
src/libs/indexed-db/openDB.js
src/tests/watchlist-view/addWatchList.test.js

This introduces the framework for testing into the extension as well as adds a single test case as proof of concept.

Implement Initial testing

---

package-lock.json
package.json

Resolve security issues in dependencies shown in package-lock.json 

---

src/background/analysis/classModels.js
src/background/analysis/interactDB/addEvidence.js
src/libs/components/label-detail/components/evidence/index.js
src/options/views/about-view/components/faq.js

Fix confusing wording and making wording user friendly

---

src/background/analysis/classModels.js
src/background/background.js
src/libs/icons/index.js
src/libs/indexed-db/settings/index.js
src/popup/views/website-view/index.js
src/popup/views/website-view/style.js

Implement enabling/disabling the extension from the popup. This status is stored in the IDB so it will be persistent through browsing sessions.

implemented extension power button

---

src/background/analysis/buildUserData/importSearchData.js
src/background/analysis/classModels.js
src/libs/components/label-detail/components/item/index.js
src/libs/exportData/createBlob.js
src/libs/exportData/initiateDownload.js
src/libs/indexed-db/getAnalytics.js
src/libs/indexed-db/openDB.js
src/libs/indexed-db/settings/index.js
src/options/components/website-label-list/index.js
src/options/views/about-view/index.js
src/options/views/app-view/components/nav-bar/index.js
src/options/views/home-view/components/label-summary-card/index.js
src/options/views/home-view/index.js
src/options/views/search-view/components/filter-search/components/filters/index.js
src/options/views/search-view/index.js
src/options/views/settings-view/components/danger-settings/index.js
src/options/views/settings-view/components/data-settings/index.js
src/options/views/settings-view/components/theme-settings.js
src/options/views/settings-view/index.js
src/options/views/watchlist-view/components/edit-modal/index.js
src/options/views/watchlist-view/components/list-item/index.js
src/options/views/watchlist-view/index.js
src/popup/views/label-view/index.js
src/popup/views/website-view/index.js

Analytics Implementation Added

---

package.json
src/manifest.json

Changed the version of the extension in manifest and package.json to prepare for release.

updated version to 1.0.0

---

src/background/analysis/classModels.js
src/options/views/watchlist-view/index.js

Made requested changes to the language in our UI in order to provide users with a more accurate description of what our extension does.

small adjustments to ui language

---

src/background/analysis/interactDB/addEvidence.js

fixed the whitelisting of ipinfo/Privacy Pioneer #438

---

src/background/analysis/classModels.js
src/libs/components/label-detail/components/evidence/index.js
src/options/views/about-view/components/faq.js

Simplified and improved wording across the extension #462

---

src/libs/indexed-db/notifications.js

Fixes to notification message

---

src/options/views/settings-view/components/danger-settings/index.js
src/options/views/settings-view/components/data-settings/index.js
src/options/views/settings-view/components/toggle-switch.js
src/options/views/watchlist-view/components/list-item/index.js
src/options/views/watchlist-view/components/list-item/style.js

This PR closes #463. It includes minor cosmetic adjustments to the tooltip throughout the extension as suggested in https://docs.google.com/document/d/11OabxTYA8K2Txb8A0bnRZM7dcMvaMJXVNPyXB856OAU/edit.

Tooltip Adjustments 

---

src/libs/tour/exData.json
src/libs/tour/index.js

removed the ipinfo slide from tour #483

---

src/libs/tour/index.js

removed skip and back buttons

---

src/libs/indexed-db/settings/index.js
src/options/views/home-view/index.js

I added a simple alert to the homepage that only runs on the first visit.

added alert on first visit of the homepage

---

src/libs/indexed-db/notifications.js
src/libs/indexed-db/settings/index.js
src/libs/indexed-db/updateWatchlist.js
src/manifest.json
src/options/views/watchlist-view/components/edit-modal/index.js
src/options/views/watchlist-view/components/list-item/index.js
src/options/views/watchlist-view/index.js

See issue #482 for a checklist of changes made

Issue 482 - Fixed Notifications

---

src/background/analysis/interactDB/addEvidence.js
src/libs/components/label-detail/components/evidence/index.js
src/popup/views/website-view/index.js

Issue 490 - Show Current Browsing Session Evidence

---

README.md
package-lock.json
src/background/analysis/classModels.js
src/options/views/home-view/index.js
src/options/views/settings-view/components/data-settings/index.js

511, 509 addressed. Review specifically requested on README new writing and tooltip changes
close #509 on merge
close #511 on merge

Tooltip, README GPS and npm warn

---

src/options/views/home-view/components/label-summary-card/index.js

Fixed Label Language in Home View

---

README.md

readme adjustments #535

---

src/background/analysis/buildUserData/importSearchData.js

Any instance of a phone number being detected will now show up in the extension. When reviewing can someone confirm the notifications work for phone number. Closes issue #526

Fixed Phone Number Notification

---

package-lock.json
package.json

This will close dependabot issue 62

Updated @babel/traverse package

---

src/libs/indexed-db/notifications.js

Custom watchlist keywords should now send notifications

personal notifications hash ref fixed

---

src/background/analysis/classModels.js
src/options/views/watchlist-view/components/edit-modal/components/forms.js
src/options/views/watchlist-view/components/edit-modal/components/input-validators.js
src/options/views/watchlist-view/components/edit-modal/index.js

Allow no address

---

package-lock.json
package.json

bumped web-ext to 7.10.0

---

src/background/analysis/interactDB/ml/jsrun.js

Will close privacy-tech-lab/privacy-pioneer-web-crawler#20

Issue20crawler

---

README.md

Updates to the Known issues section of the readme, related to #582 .

Update Readme #582

---

src/background/analysis/interactDB/ml/jsrun.js

This pull request includes changes to the `src/background/analysis/interactDB/ml/jsrun.js` file to improve input normalization and ensure consistent tokenization.

Updated the input clean up (issue #595)
